# [tag:starship-config-toml]

# https://starship.rs/config/#prompt

right_format = '$env_var'

[character]
# https://starship.rs/config/#character
error_symbol = '[](bold red)'

[battery]
# https://starship.rs/config/#battery
discharging_symbol = '󰁽 '
charging_symbol = '[󰂈 ](green)'
unknown_symbol = '󰂑 '
empty_symbol = '󱃍 '

[[battery.display]]
threshold = 30
discharging_symbol = '󱃍 '
charging_symbol = '[󱊤 ](green)'

[gcloud]
# https://starship.rs/config/#google-cloud-gcloud
disabled = true

[git_status]
stashed = ''

[env_var.HEROKU_APP]
format = '[ $env_value](fg:purple)'

[env_var.BW_SESSION]
format = '[󱦃 BITWARDEN](fg:red)'

# [username]
# # https://starship.rs/config/#username
# show_always = true
# style_user = 'dimmed blue'
# format = '[$user@]($style)'

# [hostname]
# # https://starship.rs/config/#hostname
# ssh_only = false
# style = 'dimmed blue'
# format = '[$ssh_symbol$hostname]($style) '

# [localip]
# # https://starship.rs/config/#local-ip
# disabled = false
# ssh_only = false
# style = 'dimmed blue'
# format = '[$localipv4]($style)'
